# ************************************************************
# Sequel Ace SQL dump
# Version 3038
#
# https://sequel-ace.com/
# https://github.com/Sequel-Ace/Sequel-Ace
#
# Host: 127.0.0.1 (MySQL 8.0.26)
# Database: bibliophile
# Generation Time: 2021-08-05 21:33:04 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
SET NAMES utf8mb4;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE='NO_AUTO_VALUE_ON_ZERO', SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table books
# ------------------------------------------------------------

DROP TABLE IF EXISTS `books`;

CREATE TABLE `books` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `title` char(255) DEFAULT NULL,
  `year` int DEFAULT NULL,
  `author` char(255) DEFAULT NULL,
  `genre` char(100) DEFAULT NULL,
  `cover_url` text,
  `rating` float DEFAULT NULL,
  `pdf_url` text,
  `description` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

LOCK TABLES `books` WRITE;
/*!40000 ALTER TABLE `books` DISABLE KEYS */;

INSERT INTO `books` (`id`, `title`, `year`, `author`, `genre`, `cover_url`, `rating`, `pdf_url`, `description`)
VALUES
	(5,'Hamlet',1603,'William Shakespeare','History','https://covers.openlibrary.org/b/id/10965676-L.jpg',3.75,'https://archive.org/download/bub_gb_-IafnF65cNYC/bub_gb_-IafnF65cNYC.pdf','In this quintessential Shakespeare tragedy, a young prince\'s halting pursuit of revenge for the murder of his father unfolds in a series of highly charged confrontations that have held audiences spellbound for nearly four centuries. Those fateful exchanges, and the anguished soliloquies that precede and follow them, probe depths of human feeling rarely sounded in any art.The title role of Hamlet, perhaps the most demanding in all of Western drama, has provided generations of leading actors their greatest challenge. Yet all the roles in this towering drama are superbly delineated, and each of the key scenes offers actors a rare opportunity to create theatrical magic. As if further evidence of Shakespeare\'s genius were needed, Hamlet is a unique pleasure to read as well as to see and hear performed. The full text of this extraordinary drama is reprinted here from an authoritative British edition complete with illuminating footnotes.'),
	(6,'Utopia',1518,'Thomas More','Fiction','https://covers.openlibrary.org/b/id/9601076-L.jpg',2.25,'https://archive.org/download/utopia1893more/utopia1893more.pdf','First published in 1516, Thomas More\'s Utopia is one of the most important works of European humanism. Through the voice of the mysterious traveler Raphael Hythloday, More describes a pagan, communist city-state governed by reason. Addressing such issues as religious pluralism, women\'s rights, state-sponsored education, colonialism, and justified warfare, Utopia seems remarkably contemporary nearly five centuries after it was written, and it remains a foundational text in philosophy and political theory.'),
	(7,'Tamburlaine the Greate',1605,'Christopher Marlowe','Drama','https://covers.openlibrary.org/b/id/8243955-L.jpg',0.5,'https://archive.org/download/tamburlainegreat1605marl/tamburlainegreat1605marl.pdf','The Tragical History of the Life and Death of Doctor Faustus, commonly referred to simply as Doctor Faustus, is an Elizabethan tragedy by Christopher Marlowe, based on German stories about the title character Faust, that was first performed sometime between 1588 and Marlowe\'s death in 1593. Two different versions of the play were published in the Jacobean era, several years later. The powerful effect of early productions of the play is indicated by the legends that quickly accrued around them—that actual devils once appeared on the stage during a performance, (to the great amazement of both the actors and spectators), a sight that was said to have driven some spectators mad.'),
	(8,'The essays of Michel de Montaigne',1600,'Michel de Montaigne','Philosophy','https://ia800907.us.archive.org/BookReader/BookReaderPreview.php?id=essaysofmichelde02montuoft&itemPath=%2F32%2Fitems%2Fessaysofmichelde02montuoft&server=ia800907.us.archive.org&page=cover_w500_h500.jpg',4.24,'https://archive.org/download/essaysofmichelde02montuoft/essaysofmichelde02montuoft.pdf','In 1572 Montaigne retired to his estates in order to devote himself to leisure, reading and reflection. There he wrote his constantly expanding \'assays\', inspired by the ideas he found in books contained in his library and from his own experience. He discusses subjects as diverse as war-horses and cannibals, poetry and politics, sex and religion, love and friendship, ecstasy and experience. But, above all, Montaigne studied himself as a way of drawing out his own inner nature and that of men and women in general. The Essays are among the most idiosyncratic and personal works in all literature and provide an engaging insight into a wise Renaissance mind, continuing to give pleasure and enlightenment to modern readers.'),
	(9,'The Divine Comedy.',1472,'Dante Alighieri','Poetry','https://assets.fontsinuse.com/static/use-media-items/42/41521/upto-700xauto/577b7f1e/Dante%20the%20Divine%20Comedy%20front.jpeg',4,'https://archive.org/details/oxfdivinecom00dantuoft?ref=ol&view=theater','Dante’s Divine Comedy is a trilogy of poems charting the poet’s journey from hell (Inferno) through Purgatory (Purgatorio) to heaven (Paradiso), guided by his fellow poet, Virgil. Featuring lakes of filth and farting demons, it’s much more fun than its theological subject might suggest.'),
	(10,'The faerie queene',1590,'Edmund Spenser','Poetry','https://ia800302.us.archive.org/view_archive.php?archive=/31/items/olcovers613/olcovers613-L.zip&file=6133754-L.jpg',3.57,'https://archive.org/download/faeriequeenedispo00spen/faeriequeenedispo00spen.pdf','The Faerie Queene was the first epic in English and one of the most influential poems in the language for later poets from Milton to Tennyson. Dedicating his work to Elizabeth I, Spenser brilliantly united medieval romance and renaissance epic to expound the glory of the Virgin Queen. The poem recounts the quests of knights including Sir Guyon, Knight of Constance, who resists temptation, and Artegall, Knight of Justice, whose story alludes to the execution of Mary Queen of Scots. Composed as an overt moral and political allegory, The Faerie Queene, with its dramatic episodes of chivalry, pageantry and courtly love, is also a supreme work of atmosphere, colour and sensuous description.'),
	(11,'Orlando furioso',1557,'Lodovico Ariosto','Poetry','https://ia800602.us.archive.org/view_archive.php?archive=/10/items/olcovers573/olcovers573-L.zip&file=5735511-L.jpg',4.03,'https://archive.org/download/orlandofuriosoin01arioiala/orlandofuriosoin01arioiala.pdf','The only unabridged prose translation of Ariosto\'s Orlando Furioso - a witty parody of the chivalric legends of Charlemagne and the Saracen invasion of France - this version faithfully recaptures the entire narrative and the subtle meanings behind it.'),
	(12,'The Travels',1300,'Marco Polo, Ronald E. Latha','Literature','https://ia600609.us.archive.org/view_archive.php?archive=/8/items/olcovers598/olcovers598-L.zip&file=5983997-L.jpg',1,'https://archive.org/details/travelsofmarcopo00polo?ref=ol&view=theater','Join the 13th century merchants Marco, Niccolo and Maffeo Polo as they journey from their native city of Venice to the faraway land of Cathay, or China. There, young Marco will meet Kublai Khan, the ruler of the vast Mongolian empire. Read about his many adventures serving the Khan in the lands East of Europe, and his adventures coming back home to Venice. This medieval book, dictated by Marco while imprisoned in Genoa, was one of the inspirations of the Age of Exploration during the Renaissance, and it still intrigues readers today to learn of the Polo\'s adventures in the far East.'),
	(13,'Torinensis De revolutionibus orbium coelestium libri VI',1543,'Nicolaus Copernicus','Science','https://covers.openlibrary.org/b/id/7895546-L.jpg',4.5,'https://archive.org/download/nicolaicopernici00cope_1/nicolaicopernici00cope_1.pdf','The Ptolemaic system of the universe, with the earth at the center, had held sway since antiquity as authoritative in philosophy, science, and church teaching. Following his observations of the heavenly bodies, Nicolaus Copernicus (1473-1543) abandoned the geocentric system for a heliocentric model, with the sun at the center. His remarkable work, On the Revolutions of Heavenly Spheres, stands as one of the greatest intellectual revolutions of all time, and profoundly influenced, among others, Galileo and Sir Isaac Newton.'),
	(14,'Romeo And Juliet',1597,'William Shakespeare','Romance','https://lh3.googleusercontent.com/proxy/GZC6ZPSvZmc2Y9CsoTjXRd-DQvhTo4VEJgObRQbGcEicBBIgy_ffkhXj68mvJLOE6snZDhlx5CM-0i8PoCIjYqgAuruOqAPwXunphDreuvErPSc',1.35,'https://archive.org/details/mostexcellentlam00shak/page/n7/mode/2up?ref=ol&view=theater','In Romeo and Juliet, Shakespeare creates a violent world, in which two young people fall in love. It is not simply that their families disapprove; the Montagues and the Capulets are engaged in a blood feud. In this death-filled setting, the movement from love at first sight to the lovers’ final union in death seems almost inevitable. And yet, this play set in an extraordinary world has become the quintessential story of young love. In part because of its exquisite language, it is easy to respond as if it were about all young lovers.'),
	(15,'Beowulf',900,'Unknown','Poetry','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327878125l/52357.jpg',3.46,'https://archive.org/details/beowulfwithfinns00beowuoft?ref=ol&view=theater','Beowulf is a major epic of Anglo-Saxon literature, probably composed between the first half of the seventh century and the end of the first millennium. The poem was inspired by Germanic and Anglo-Saxon oral tradition recounting the exploits of Beowulf, the hero who gave his name to the poem. Here, it\'s transcribed as a verse epic, onto which are grafted Christian additions.'),
	(16,'La mandragola',1554,'Niccolò Machiavelli','Philosophy','https://covers.openlibrary.org/b/id/8151778-L.jpg',3.52,'https://archive.org/download/lamandragolacome00mach/lamandragolacome00mach.pdf','Capolavoro della commedia rinascimentale, la Mandragola fu composta da Machiavelli dopo il suo allontanamento forzoso dalla politica. La vicenda ruota intorno alla beffa giocata da un giovane fiorentino a un marito sciocco per possederne la moglie di cui si era invaghito. Un ruolo determinante nel convincimento della donna ha il suo confessore, corrotto dai denari dell\'amante. Nella commedia il tema realistico della beffa, di matrice boccacciana, si rapprende in una perfetta macchina teatrale, rispettosa fin nei particolari più minuti delle regole della commedia antica (Plauto e Terenzio). Attraverso il format della commedia Machiavelli tenta di definire un\'antropologia della vita quotidiana, analogamente a come nelle opere politiche veniva descrivendo l\'antropologia del potere. Si scopre così che non c\'è differenza tra una sfera e l\'altra: sono sempre e soltanto l\'utile e il piacere a muovere gli uomini. Quando però il simulare e il dissimulare dell\'agire politico si trasferiscono nella quotidianità, la realtà si fa doppia o tripla, nascono situazioni paradossali che sono di per sé comiche. Il paradosso tocca i valori della famiglia, della morale privata, della religione. Prendono forma le prime creature fredde e amorali della letteratura moderna, senza che nulla venga sottratto alla vivacità e al divertimento. La Mandragola è presentata qui in un nuovo testo critico e con un commento per la prima volta esauriente.'),
	(17,'The Odyssey',800,'Homer','Classics','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1390173285l/1381.jpg',3.78,'https://archive.org/details/odysseybookiv00home?ref=ol&view=theater','Sing to me of the man, Muse, the man of twists and turns driven time and again off course, once he had plundered the hallowed heights of Troy.So begins Robert Fagles\' magnificent translation of the Odyssey. If the Iliad is the world\'s greatest war epic, then the Odyssey is literature\'s grandest evocation of everyman\'s journey though life. Odysseus\' reliance on his wit and wiliness for survival in his encounters with divine and natural forces, during his ten-year voyage home to Ithaca after the Trojan War, is at once a timeless human story and an individual test of moral endurance. In the myths and legends that are retold here, Fagles has captured the energy and poetry of Homer\'s original in a bold, contemporary idiom, and given us an Odyssey to read aloud, to savor, and to treasure for its sheer lyrical mastery. Renowned classicist Bernard Knox\'s superb Introduction and textual commentary provide new insights and background information for the general reader and scholar alike, intensifying the strength of Fagles\' translation.This is an Odyssey to delight both the classicist and the public at large, and to captivate a new generation of Homer\'s students.'),
	(18,'Godfrey of Bulloigne; or, The recovery of Jerusalem',1581,'Torquato Tasso','Poetry','https://ia800602.us.archive.org/view_archive.php?archive=/8/items/olcovers569/olcovers569-L.zip&file=5699099-L.jpg',3.89,'https://archive.org/download/godfreyofbulloig00tassrich/godfreyofbulloig00tassrich.pdf','Arguably the greatest Italian poet after Dante, Torquato Tasso was born in Sorrento in 1544 and died in Rome in 1595, having served as the court poet in Ferrara, been confined for years in a madhouse after attacking a servant with a knife, and composed one of the great works of Renaissance literature. Unjustly neglected today, Tasso\'s epic poem \'Jerusalem Delivered\'(first published in 1581) is set in the 11th century and tells the story of the First Crusade and the siege which gave Christian armies control over Jerusalem and the Holy Lands for a time. As in other epic poems, \'Jerusalem Delivered\' deftly mixes history and myth. Tasso\'s heroes - Godfrey, leader of the Christian armies; Rinaldo, bravest of the Christian warriors; and Tancred, the Italian prince who falls in love with the pagan warrioress Clorinda, whom he eventually (and simultaneously) converts and kills - must face not only the Saracens and their allies, but also a host of fearsome and manipulative devils, demons, and sorcerers. This is a sweeping and often thrilling tale of war, faith, love, and sex that easily rivals its classical predecessors. Writing at a time when Christianity was bitterly divided, Tasso was naturally concerned with the nature of leadership and loyalty, with the importance of sacrifice, with the evils of corruption, and with the existence of truth, themes that continue to resonate today.'),
	(19,'Tempest',1611,'William Shakespeare','Drama','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546081115l/12985.jpg',3.8,'https://archive.org/details/shakespearedrama00shak?ref=ol&view=theater','The Tempest is a play by William Shakespeare, believed to have been written in 1610–11, and thought by many critics to be the last play that Shakespeare wrote alone. It is set on a remote island, where Prospero, the rightful Duke of Milan, plots to restore his daughter Miranda to her rightful place using illusion and skilful manipulation. He conjures up a storm, the eponymous tempest, to lure his usurping brother Antonio and the complicit King Alonso of Naples to the island. There, his machinations bring about the revelation of Antonio\'s lowly nature, the redemption of the King, and the marriage of Miranda to Alonso\'s son, Ferdinand.'),
	(20,'Love for love',1695,'William Congreve','Drama','https://covers.openlibrary.org/b/id/8089916-L.jpg',4,'https://archive.org/download/godfreyofbulloig00tassrich/godfreyofbulloig00tassrich.pdf','Love for Love is a Restoration comedy written by British playwright William Congreve. It premiered on 30 April 1695 at Betterton\'s Co., Lincoln\'s Inn Fields. The play is a comical farce enlivened by its witty dialogue and its humorous characters, and perhaps more successful in its day than The Way of the World, now considered Congreve\'s best. The main character is Valentine, then Jeremy, Valentine\'s resourceful servant; Sir Sampson, with his \'blunt vivacity\'; Ben, the rough young sea-dog, who intends to marry whom he chooses; Miss Prue, only too ready to learn the lessons in love given her by Tattle, the vain, half-witted beau, who finds himself married to Mrs. Frail, the lady of easy virtue, when he thinks he has captured Angelica; and Foresight, the gullible old astrologer.'),
	(21,'Twelfth Night',1601,'William Shakespeare','Classics','https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1561384026l/1625._SY475_.jpg',3.98,'https://archive.org/details/shakespearedrama00shak?ref=ol&view=theater','Named for the twelfth night after Christmas, the end of the Christmas season, Twelfth Night plays with love and power. The Countess Olivia, a woman with her own household, attracts Duke (or Count) Orsino. Two other would-be suitors are her pretentious steward, Malvolio, and Sir Andrew Aguecheek.Onto this scene arrive the twins Viola and Sebastian; caught in a shipwreck, each thinks the other has drowned. Viola disguises herself as a male page and enters Orsino’s service. Orsino sends her as his envoy to Olivia—only to have Olivia fall in love with the messenger. The play complicates, then wonderfully untangles, these relationships.'),
	(22,'Introduction to a devout life, to which is prefixed an abstract of his life',1662,'Francis de Sales','Literature','https://covers.openlibrary.org/b/id/8942082-L.jpg',3.24,'https://archive.org/download/introductiontode00franuoft/introductiontode00franuoft.pdf','Introduction to the Devout Life (French: Introduction à la vie dévote) is a book written by Saint Francis de Sales, the first edition being published in 1609. The final edition was published in 1619, prior to the death of Francis in 1622. It enjoyed wide popularity, and was well received in both Protestant and Catholic circles, evidenced by its translation into all major languages of the day. It is typically categorized as a form of reading known as lectio divina (divine reading), based on the Christian monastic practice of spiritual reading. Like The Imitation of Christ by Thomas a Kempis, it is considered a spiritual classic in the Christian tradition. The work is also used as a guide in Christian spiritual direction.'),
	(23,'A Midsummer Night\'s Dream',1600,'William Shakespeare','Classics','https://covers.openlibrary.org/b/id/8785744-L.jpg',3.95,'https://archive.org/details/shakespearesmids03shak?ref=ol&view=theater','One night two young couples run into an enchanted forest in an attempt to escape their problems. But these four humans do not realize that the forest is filled with fairies and hobgoblins who love making mischief. When Oberon, the Fairy King, and his loyal hobgoblin servant, Puck, intervene in human affairs, the fate of these young couples is magically and hilariously transformed. Like a classic fairy tale, this retelling of William Shakespeare\'s most beloved comedy is perfect for older readers who will find much to treasure and for younger readers who will love hearing the story read aloud.'),
	(24,'Aesop\'s Fables',560,'Aesop','Fiction','https://covers.openlibrary.org/b/id/8241462-L.jpg',4.33,'https://archive.org/details/aesopsfablesvoli02aeso?ref=ol&view=theater','Aesop fables are a collection of fables credited to Aesop, a slave and story-teller believed to have lived in ancient Greece between 620 and 560 BCE. As if further evidence of Shakespeare\'s genius were needed, Hamlet is a unique pleasure to read as well as to see and hear performed. The full text of this extraordinary drama is reprinted here from an authoritative British edition complete with illuminating footnotes.'),
	(25,'Don Quixote',1600,'Miguel de Cervantes Saavedra','Fiction','https://ia600605.us.archive.org/view_archive.php?archive=/28/items/olcovers559/olcovers559-L.zip&file=5596135-L.jpg',4,'https://archive.org/details/donquixotedelama00cerviala?ref=ol&view=theater','Widely regarded as the world\'s first modern novel, Don Quixote chronicles the famous picaresque adventures of the noble knight-errant Don Quixote de La Mancha and his faithful squire, Sancho Panza, as they travel through sixteenth-century Spain. [Translated by John Ormsby.]'),
	(26,'Centuries of meditations',1665,'Thomas Traherne','Poetry','Thomas Traherne',2,'https://archive.org/details/cu31924029348012?ref=ol&view=theater','Centuries is a collection of poems written to express the rapture of life lived in accordance with God. Yet Dobell is careful to state that even though Traherne was a clergyman, there is plenty of beauty to be found in his poetry that does not require specific belief in Christianity or in God.');

/*!40000 ALTER TABLE `books` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
